# BRIGHTVALE THEME — ink on parchment

# Background & foreground
background              #e5e4d2
foreground              #2d2a18
background_opacity      0.85

# Selection
selection_foreground    #f5f5eb
selection_background    #524d27

# URLs
url_color               #c08f4e

# Window borders
active_border_color     #c08f4e
inactive_border_color   #c8c8b2
bell_border_color       #814233

# OS titlebar
wayland_titlebar_color  system

# Cursor
cursor                  #2d2a18
cursor_text_color       #f5f5eb

# 16 colors — Brightvale light theme
# black
color0                  #2d2a18
color8                  #524d27
# red
color1                  #814233
color9                  #9e5242
# green
color2                  #5a7a3a
color10                 #6e9448
# yellow
color3                  #c08f4e
color11                 #d4a865
# blue
color4                  #4c2f51
color12                 #5e3a63
# magenta
color5                  #8a8868
color13                 #524d27
# cyan
color6                  #7e8566
color14                 #9aa07e
# white
color7                  #f5f5eb
color15                 #eeeedf

# FONTS
# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size        13.0
force_ltr        no
modify_font      weight 700
